name: "MacOS build"
description: "Build and upload package for MacOS [> 10.13] systems"

runs:
    using: "composite"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            submodules: true

      - name: Setup GNU Fortran
        uses: fortran-lang/setup-fortran@v1
        id: setup-fortran

      - name: "Build: Wheels"
        uses: pypa/cibuildwheel@v2.20.0
        with:
            output-dir: dist
        env:
            FC: "/usr/local/bin/gfortran"
            CIBW_ENVIRONMENT_MACOS:
                MACOSX_DEPLOYMENT_TARGET=14.0
                PROJ_WHEEL=true
                PROJ_NETWORK=ON


      - name: "Upload: Wheel"
        uses: actions/upload-artifact@v3
        with:
            name: "macos_x86_64_wheel"
            path: ./dist/*

