name: "Publish documentation"
description: "Build and publish the documentation for github page"

inputs:
    GITHUB_TOKEN:
        required: true
    python-version:
        description: 'Python version for installation'
        required: true
    package-name:
        description: 'Name of the package to install'
        required: true


runs:
    using: "composite"
    steps:
      - uses: MartinPdeS/MPSActions/install_package_on_manylinux@master
        with:
            python-version: ${{ inputs.python-version }}
            package-name: ${{ inputs.package-name }}

      - uses: actions/checkout@v4
        with:
            sparse-checkout: |
              docs
              requirements

      - name: "Build: documentation"
        shell: bash
        run: |
            make -C docs html

      - name: "Upload: GitHub Pages"
        uses: crazy-max/ghaction-github-pages@v3
        with:
            target_branch: gh-pages
            build_dir: docs/build/html
        env:
            GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
