name: "ManyLinux build"
description: "Build and upload package for ManyLinux systems"

inputs:
    python-version:
        description: 'Python version for installation'
        type: string
        required: true

runs:
    using: "composite"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
            submodules: 'true'

      - uses: MartinPdeS/MPSActions/interpret_python_version@master
        with:
          python-version: ${{ inputs.python-version }}

      - name: "Build: Wheels"
        uses: pypa/cibuildwheel@v2.16.2
        with:
            output-dir: dist
        env:
            CC: "/usr/bin/gcc"
            CXX: "/usr/bin/g++"
            # CIBW_BUILD: "${{ env.PYTHON_CP_VERSION }}-manylinux_x86_64"
            CIBW_BEFORE_TEST: ls . && ls {project}/

      - name: "Upload: Wheel"
        uses: actions/upload-artifact@v3
        with:
            name: "manylinux_wheel_python${{ env.PYTHON_CP_VERSION }}"
            path: ./dist/*
