name: "ManyLinux build"
description: "Build and upload package for ManyLinux systems"

runs:
    using: "composite"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
            submodules: 'true'

      - name: "Build: Wheels"
        uses: pypa/cibuildwheel@v2.17.0
        with:
            output-dir: dist
        env:
            CC: "/usr/bin/gcc"
            CXX: "/usr/bin/g++"
            CIBW_TEST_SKIP: 'tests'

      - name: "Upload: Wheel"
        uses: actions/upload-artifact@v3
        with:
            name: "manylinux_wheel_python"
            path: ./dist/*
