name: "Compute test coverage"
description: "Interprets python version written with a dot to cp version"

runs:
  using: "composite"
  steps:
      - name: "Computing total coverage"
        run: |
          python -m pip install coverage pytests
          cd tests
          coverage run -p -m pytest -s .
          coverage combine
          coverage report -m --skip-covered
          coverage json -o ./CoverageReport.json
          export TOTAL=$(python -c "import json; print(json.load(open('CoverageReport.json'))['totals']['percent_covered_display'])")
          echo "total=$TOTAL" >> $GITHUB_ENV