name: "Install package on ManyLinux"
description: "Installs prebuild ubuntu-latest wheel to current job"

inputs:
    python-version:
        description: 'Python version for installation'
        required: true
    package-name:
        description: 'Name of the package to install'
        required: true

runs:
    using: "composite"
    steps:
      - uses: MartinPdeS/MPSActions/interpret_python_version@master
        with:
            python-version: ${{ inputs.python-version }}

      - name: "Set-up: Python ${{ env.cp_python_version }}"
        uses: actions/setup-python@v4
        id: cp310
        with:
            python-version: "${{ env.dotted_python_version }}"

      - name: "Install: Dependencies for headless server"
        shell: bash
        run: |
            sudo apt-get update
            sudo apt-get install libgl1-mesa-glx xvfb

      - name: "Chekcout requirements and files for testting"
        uses: actions/checkout@v4

      - name: "Download: wheel"
        uses: actions/download-artifact@v3
        with:
            path: ./dist

      - name: "Install package"
        shell: bash
        run: |
            python -m pip install --find-links './dist/manylinux_wheel_python/' '${{ inputs.package-name }}[documentation,testing]'
