name: "MacOS build"
description: "Build and upload package for MacOS [> 10.13] systems"

inputs:
    python-version:
        description: 'Python version for installation'
        type: string
        required: true

runs:
    using: "composite"

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
            submodules: true

      - uses: msys2/setup-msys2@v2
        with:
            update: true
            install: >-
                mingw-w64-x86_64-toolchain
                mingw-w64-x86_64-cmake
                mingw-w64-x86_64-openmp
                mingw-w64-x86_64-ninja

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: "Build: Wheels"
        uses: pypa/cibuildwheel@v2.16.2
        with:
            output-dir: dist
        env:
            CIBW_BEFORE_BUILD: 'echo "C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/x86_64-w64-mingw32/lib/" >> $GITHUB_PATH
                            && mkdir build
                            && cd build
                            && cmake -G"Ninja" DCMAKE_Fortran_COMPILER=C:/mingw64/bin/gfortran.exe -DCMAKE_FIND_DEBUG_MODE=1 -DPYBIND11_PYTHON_VERSION=${{ inputs.python-version }}  ./..
                            && ninja
                            && cd ..
                            && python -m pip install .'

      - name: "Upload: Wheel"
        uses: actions/upload-artifact@v3
        with:
            name: "windows_wheel_python"
            path: ./dist/*



